// Import necessary modules and CSS
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./component/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Define the RootLayout component with proper layout using flexbox
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={" flex min-h-screen bg-f5f5f5"}>
        <Sidebar />
        <div className="flex-grow">
          {children} {/* This will be the main content area */}
        </div>
      </body>
    </html>
  );
}
